/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_text_util_ArabicShaper */

#ifndef _Included_android_text_util_ArabicShaper
#define _Included_android_text_util_ArabicShaper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_text_util_ArabicShaper
 * Method:    reorderReshapeBidiText
 * Signature: ([C[CII)I
 */
JNIEXPORT jint JNICALL Java_android_text_util_ArabicShaper_reorderReshapeBidiText
  (JNIEnv *, jclass, jcharArray, jcharArray, jint, jint);

/*
 * Class:     android_text_util_ArabicShaper
 * Method:    reshapeArabicText
 * Signature: ([C[CII)I
 */
JNIEXPORT jint JNICALL Java_android_text_util_ArabicShaper_reshapeArabicText
  (JNIEnv *, jclass, jcharArray, jcharArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
